import 'package:flutter/material.dart';
import 'package:provider/provider.dart';
import '../../logic/settings/language_provider.dart';

class AppTranslations {
  static const Map<String, Map<String, String>> _keys = {
    'vi': {
      'app_title': 'Ứng dụng của tôi',
      'settings': 'Cài đặt',
      'language': 'Ngôn ngữ',
      'chat_preview': 'Đoạn chat preview!',
      'login': 'Đăng nhập',
      'gmail': 'Gmail',
      'input_gmail': 'Nhập Gmail tại đây',
      'password': 'Mật khẩu',
      'input_password': 'Nhập mật khẩu tại đây',
      'create_account': 'Tạo tài khoản',
      'main_screen': 'Màn hình chính',
      'messages': 'Tin nhắn',
      'contact': 'Liên hệ',
      'notifications': 'Thông báo',
      'about': 'Giới thiệu',
      'page_content': 'Nội dung trang',
      'no_notifications': 'Chưa có thông báo.',
      'enter_message': 'Nhập tin nhắn...',
      'account': 'Tài khoản',
      'notification': 'Thông báo',
      'security': 'Bảo mật',
      'theme': 'Giao diện',
      'storage': 'Lưu trữ',
      'battery': 'Tiết kiệm pin',
      'about_app': 'Thông tin ứng dụng',
      'screen_mode': 'Chế độ màn hình',
      'light': 'Sáng',
      'dark': 'Tối',
      'system': 'Hệ thống',
      'chat_color': 'Màu chủ đề đoạn chat (Sắp ra mắt)',
      'choose_language': 'Chọn ngôn ngữ',
      'phone': 'Số điện thoại',
      'birthday': 'Ngày sinh',
      'gender': 'Giới tính',
      'male': 'Nam',
      'push_notification': 'Thông báo đẩy',
      'push_notification_desc': 'Nhận thông báo qua ứng dụng',
      'email_notification': 'Thông báo email',
      'email_notification_desc': 'Nhận thông báo qua email',
      'sms_notification': 'Thông báo SMS',
      'sms_notification_desc': 'Nhận thông báo qua tin nhắn',
      'change_password': 'Đổi mật khẩu',
      'fingerprint': 'Vân tay / Face ID',
      'app_lock': 'Khóa ứng dụng',
      'auto_lock_after': 'Tự động khóa sau',
      'auto_lock_time': 'Thời gian khóa tự động',
      'feature_developing': 'Tính năng đang phát triển',
      'app_version': 'Phiên bản ứng dụng',
      'minutes': 'phút',
      'used_storage': 'Dung lượng đã dùng',
      'images': 'Hình ảnh',
      'video': 'Video',
      'audio': 'Âm thanh',
      'documents': 'Tài liệu',
      'power_save_mode': 'Chế độ tiết kiệm pin',
      'power_save_desc': 'Giảm hiệu năng để kéo dài thời gian dùng',
      'current_battery': 'Mức pin hiện tại',
      'remaining_time': 'Thời gian còn lại',
      'version': 'Phiên bản',
      'developer': 'Nhà phát triển',
      'team1': 'Nhóm 1',
      'description': 'Mô tả',
      'app_description': 'Ứng dụng quản lý thông minh',
      'copyright': '© 2026 Nhóm 1. Tất cả quyền được bảo lưu.',
      'contacts': 'Liên hệ',
      'search_contact': 'Tìm kiếm liên hệ...',
      'search': 'Tìm kiếm...',
      'create_group': 'Tạo nhóm mới',
      'invite_friends': 'Mời bạn bè sử dụng app',
      'add_friend': 'Thêm bạn mới',
      'mark_all_read': 'Đánh dấu tất cả là đã đọc',
      'inbox': 'Hộp thư',
    },
    'en': {
      'app_title': 'My Application',
      'settings': 'Settings',
      'language': 'Language',
      'chat_preview': 'Chat preview!',
      'login': 'Login',
      'gmail': 'Gmail',
      'input_gmail': 'Input Gmail Here',
      'password': 'Password',
      'input_password': 'Input Password Here',
      'create_account': 'Create Account',
      'main_screen': 'Main Screen',
      'messages': 'Messages',
      'contact': 'Contact',
      'notifications': 'Notifications',
      'about': 'About',
      'page_content': 'Page content',
      'no_notifications': 'No notifications yet.',
      'enter_message': 'Enter message...',
      'account': 'Account',
      'notification': 'Notification',
      'security': 'Security',
      'theme': 'Theme',
      'storage': 'Storage',
      'battery': 'Battery Saver',
      'about_app': 'About',
      'screen_mode': 'Screen Mode',
      'light': 'Light',
      'dark': 'Dark',
      'system': 'System',
      'chat_color': 'Chat Accent Color (Coming Soon)',
      'choose_language': 'Choose Language',
      'phone': 'Phone',
      'birthday': 'Birthday',
      'gender': 'Gender',
      'male': 'Male',
      'push_notification': 'Push Notifications',
      'push_notification_desc': 'Receive notifications via app',
      'email_notification': 'Email Notifications',
      'email_notification_desc': 'Receive notifications via email',
      'sms_notification': 'SMS Notifications',
      'sms_notification_desc': 'Receive notifications via SMS',
      'change_password': 'Change Password',
      'fingerprint': 'Fingerprint / Face ID',
      'app_lock': 'App Lock',
      'auto_lock_after': 'Auto Lock After',
      'auto_lock_time': 'Auto Lock Timeout',
      'feature_developing': 'Feature under development',
      'app_version': 'App Version',
      'minutes': 'minutes',
      'used_storage': 'Used Storage',
      'images': 'Images',
      'video': 'Video',
      'audio': 'Audio',
      'documents': 'Documents',
      'power_save_mode': 'Power Saving Mode',
      'power_save_desc': 'Reduce performance to extend battery life',
      'current_battery': 'Current Battery Level',
      'remaining_time': 'Remaining Time',
      'version': 'Version',
      'developer': 'Developer',
      'team1': 'Team 1',
      'description': 'Description',
      'app_description': 'Smart management application',
      'copyright': '© 2026 Team 1. All rights reserved.',
      'contacts': 'Contacts',
      'search_contact': 'Search contacts...',
      'search': 'Search...',
      'create_group': 'Create New Group',
      'invite_friends': 'Invite friends to use the app',
      'add_friend': 'Add New Friend',
      'mark_all_read': 'Mark all as read',
      'inbox': 'Inbox',
    },
    'ja': {
      'app_title': 'マイアプリ',
      'settings': '設定',
      'language': '言語',
      'chat_preview': 'チャットプレビュー！',
      'login': 'ログイン',
      'gmail': 'Gmail',
      'input_gmail': 'Gmailを入力してください',
      'password': 'パスワード',
      'input_password': 'パスワードを入力してください',
      'create_account': 'アカウント作成',
      'main_screen': 'メイン画面',
      'messages': 'メッセージ',
      'contact': '連絡先',
      'notifications': '通知',
      'about': '概要',
      'page_content': 'ページコンテンツ',
      'no_notifications': '通知はまだありません。',
      'enter_message': 'メッセージを入力...',
      'account': 'アカウント',
      'notification': '通知',
      'security': 'セキュリティ',
      'theme': 'テーマ',
      'storage': 'ストレージ',
      'battery': 'バッテリー節約',
      'about_app': 'アプリについて',
      'screen_mode': '画面モード',
      'light': 'ライト',
      'dark': 'ダーク',
      'system': 'システム',
      'chat_color': 'チャットアクセントカラー（近日公開）',
      'choose_language': '言語を選択',
      'phone': '電話番号',
      'birthday': '生年月日',
      'gender': '性別',
      'male': '男性',
      'push_notification': 'プッシュ通知',
      'push_notification_desc': 'アプリから通知を受信',
      'email_notification': 'メール通知',
      'email_notification_desc': 'メールで通知を受信',
      'sms_notification': 'SMS通知',
      'sms_notification_desc': 'SMSで通知を受信',
      'change_password': 'パスワード変更',
      'fingerprint': '指紋 / Face ID',
      'app_lock': 'アプリロック',
      'auto_lock_after': '自動ロック',
      'auto_lock_time': '自動ロックタイムアウト',
      'feature_developing': '機能は開発中です',
      'app_version': 'アプリバージョン',
      'minutes': '分',
      'used_storage': '使用済みストレージ',
      'images': '画像',
      'video': '動画',
      'audio': '音声',
      'documents': 'ドキュメント',
      'power_save_mode': 'バッテリー節約モード',
      'power_save_desc': 'パフォーマンスを低下させてバッテリー寿命を延長',
      'current_battery': '現在のバッテリーレベル',
      'remaining_time': '残り時間',
      'version': 'バージョン',
      'developer': '開発者',
      'team1': 'チーム1',
      'description': '説明',
      'app_description': 'スマート管理アプリ',
      'copyright': '© 2026 チーム1. All rights reserved.',
      'contacts': '連絡先',
      'search_contact': '連絡先を検索...',
      'search': '検索...',
      'create_group': '新しいグループを作成',
      'invite_friends': '友達をアプリに招待',
      'add_friend': '新しい友達を追加',
      'mark_all_read': 'すべて既読にする',
      'inbox': '受信トレイ',
    },
    'ko': {
      'app_title': '내 앱',
      'settings': '설정',
      'language': '언어',
      'chat_preview': '채팅 미리보기!',
      'login': '로그인',
      'gmail': 'Gmail',
      'input_gmail': 'Gmail을 입력하세요',
      'password': '비밀번호',
      'input_password': '비밀번호를 입력하세요',
      'create_account': '계정 만들기',
      'main_screen': '메인 화면',
      'messages': '메시지',
      'contact': '연락처',
      'notifications': '알림',
      'about': '정보',
      'page_content': '페이지 내용',
      'no_notifications': '아직 알림이 없습니다.',
      'enter_message': '메시지 입력...',
      'account': '계정',
      'notification': '알림',
      'security': '보안',
      'theme': '테마',
      'storage': '저장소',
      'battery': '배터리 절약',
      'about_app': '앱 정보',
      'screen_mode': '화면 모드',
      'light': '라이트',
      'dark': '다크',
      'system': '시스템',
      'chat_color': '채팅 강조 색상 (출시 예정)',
      'choose_language': '언어 선택',
      'phone': '전화번호',
      'birthday': '생년월일',
      'gender': '성별',
      'male': '남성',
      'push_notification': '푸시 알림',
      'push_notification_desc': '앱을 통해 알림 받기',
      'email_notification': '이메일 알림',
      'email_notification_desc': '이메일로 알림 받기',
      'sms_notification': 'SMS 알림',
      'sms_notification_desc': '문자로 알림 받기',
      'change_password': '비밀번호 변경',
      'fingerprint': '지문 / Face ID',
      'app_lock': '앱 잠금',
      'auto_lock_after': '자동 잠금',
      'auto_lock_time': '자동 잠금 시간',
      'feature_developing': '기능 개발 중',
      'app_version': '앱 버전',
      'minutes': '분',
      'used_storage': '사용된 저장소',
      'images': '이미지',
      'video': '비디오',
      'audio': '오디오',
      'documents': '문서',
      'power_save_mode': '배터리 절약 모드',
      'power_save_desc': '성능을 낮춰 배터리 수명 연장',
      'current_battery': '현재 배터리 수준',
      'remaining_time': '남은 시간',
      'version': '버전',
      'developer': '개발자',
      'team1': '팀 1',
      'description': '설명',
      'app_description': '스마트 관리 애플리케이션',
      'copyright': '© 2026 팀 1. All rights reserved.',
      'contacts': '연락처',
      'search_contact': '연락처 검색...',
      'search': '검색...',
      'create_group': '새 그룹 만들기',
      'invite_friends': '친구를 앱에 초대',
      'add_friend': '새 친구 추가',
      'mark_all_read': '모두 읽음으로 표시',
      'inbox': '수신함',
    },
    'zh': {
      'app_title': '我的应用',
      'settings': '设置',
      'language': '语言',
      'chat_preview': '聊天预览！',
      'login': '登录',
      'gmail': 'Gmail',
      'input_gmail': '请输入Gmail',
      'password': '密码',
      'input_password': '请输入密码',
      'create_account': '创建账户',
      'main_screen': '主屏幕',
      'messages': '消息',
      'contact': '联系人',
      'notifications': '通知',
      'about': '关于',
      'page_content': '页面内容',
      'no_notifications': '暂无通知。',
      'enter_message': '输入消息...',
      'account': '账户',
      'notification': '通知',
      'security': '安全',
      'theme': '主题',
      'storage': '存储',
      'battery': '省电模式',
      'about_app': '关于应用',
      'screen_mode': '屏幕模式',
      'light': '浅色',
      'dark': '深色',
      'system': '系统',
      'chat_color': '聊天强调色（即将推出）',
      'choose_language': '选择语言',
      'phone': '电话号码',
      'birthday': '出生日期',
      'gender': '性别',
      'male': '男性',
      'push_notification': '推送通知',
      'push_notification_desc': '通过应用接收通知',
      'email_notification': '邮件通知',
      'email_notification_desc': '通过邮件接收通知',
      'sms_notification': '短信通知',
      'sms_notification_desc': '通过短信接收通知',
      'change_password': '修改密码',
      'fingerprint': '指纹 / Face ID',
      'app_lock': '应用锁',
      'auto_lock_after': '自动锁定',
      'auto_lock_time': '自动锁定时间',
      'feature_developing': '功能开发中',
      'app_version': '应用版本',
      'minutes': '分钟',
      'used_storage': '已用存储',
      'images': '图片',
      'video': '视频',
      'audio': '音频',
      'documents': '文档',
      'power_save_mode': '省电模式',
      'power_save_desc': '降低性能以延长电池寿命',
      'current_battery': '当前电量',
      'remaining_time': '剩余时间',
      'version': '版本',
      'developer': '开发者',
      'team1': '团队1',
      'description': '描述',
      'app_description': '智能管理应用',
      'copyright': '© 2026 团队1. 保留所有权利。',
      'contacts': '联系人',
      'search_contact': '搜索联系人...',
      'search': '搜索...',
      'create_group': '创建新群组',
      'invite_friends': '邀请朋友使用应用',
      'add_friend': '添加新朋友',
      'mark_all_read': '全部标为已读',
      'inbox': '收件箱',
    },
  };

  static String getText(String key, String langCode) {
    return _keys[langCode]?[key] ?? _keys['vi']?[key] ?? key;
  }

  static String tr(BuildContext context, String key) {
    final langCode = Provider.of<LanguageProvider>(context).currentLangCode;
    return getText(key, langCode);
  }
}
